name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump')"
    steps:
    - uses: actions/checkout@v1
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: HUSKY_SKIP_INSTALL=1 yarn install
    - run: yarn build
    - name: Publish to NPM
      run: yarn publish --non-interactive
      env:
        YARN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
