name: Publish docs

on:
  push:
    branches:
      - refs/tags/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: |
        yarn run clean:node_modules
        yarn run clean:storybook-static
        HUSKY_SKIP_INSTALL=1 yarn install
    - name: Configure repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master --tags
    - name: Deploy docs
      run: |
        yarn run build-docs
        yarn run gh-deploy --repo https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
